### ISSUE TITLE
[1.18.1] Ticking Entity Crash

### ISSUE THREAD

**Issue by itsdinkd** [Insane96/InsaneLib#11]
Seems to be issue with Latest InsaneLib and Progressive Bosses (does not crash on insane lib 1.4.2) 

https://gist.github.com/CornOnTheCaleb/5b7e24d3a08338c09ccacc14826744de

As shown in the latest.log above, when the player encountered ender dragon, they crashed and are stuck in a crash loop.

**Comment by Insane96** [comment]
Downgrade to InsaneLib 1.4.2, 1.4.3 is not compatible with Progressive Bosses

**Comment by itsdinkd** [comment]
I am aware of the temporary solution (literally wrote that it doesnt crash on 1.4.2). Is this going to be fixed though or is this the permanent solution

**Comment by Insane96** [comment]
Definitely going to be fixed but probably not soon
