### ISSUE TITLE
Crash after spider web launched near me

### ISSUE THREAD

**Issue by Tyrius1** [Insane96/InsaneLib#12]
Title says most of it. I was running around and a spider shot a web at me. It landed next to me on a leaves block and as I saw the particles of it landing it crashed.

https://pastebin.com/W1qqgeAV
EnhancedAI-1.2.4-mc1.18.2
InsaneLib-1.4.6-mc1.18.2
Forge - 40.1.19

**Comment by Insane96** [comment]
Does it always happen?

**Comment by Tyrius1** [comment]
No its kinda random. I got another insanelib crash afterwards but was flying in creative. I removed iguanatweaks and mobpropertyrandomness keeping progressive bosses and enhanced ai just to see if it still happens without them.

**Comment by Insane96** [comment]
Report that crash too

**Comment by Tyrius1** [comment]
https://pastebin.com/wcLX9E56

**Comment by Insane96** [comment]
The crash mentions tons of mods, does it happen with InsaneLib/Enhanced AI only?

**Comment by Insane96** [comment]
No more response, also release a possible fix. Open it again if happens again
