### ISSUE TITLE
Recurring crashes

### ISSUE THREAD

**Issue by InteJason** [Insane96/InsaneLib#2]
Sorry about the last ticket, went to the wrong issue tracker...
Meant to send another one, which is this: https://pastebin.com/ihML57Qz
InsaneLib is the only mod that shows up in the crash report

**Comment by Insane96** [comment]
It might be an incompatiblity of some sort. Try remove mods until InsaneLib and another mod is left that gives the problem.

**Comment by InteJason** [comment]
This is a rare crash that only happens to one or two ppl playing my modpack, so it' won't be easy to recreate it even if I remove all the mods and test it myself, anything else I can do to provide more info?

**Comment by Insane96** [comment]
A list of mods

**Comment by InteJason** [comment]
It's on the bottom of the crash report along with the specific versions.

**Comment by Insane96** [comment]
Way to many mods, I can't do anything without the coulprit.

**Comment by Insane96** [comment]
The pastebin is no longer available. Gonna close the issue.
