### ISSUE TITLE
entity.insanelib.area_effect_cloud_3D

### ISSUE THREAD

**Issue by Dare-Demonai** [Insane96/InsaneLib#21]
somehow these cloud effects doesn't disappear or despawn

**Comment by Dare-Demonai** [comment]
somehow these cloud effects don't disappear or despawn

**Comment by Insane96** [comment]
What's their source?

**Comment by Dare-Demonai** [comment]
I don't remember it anymore. I was using jade to identify the source name and it's in the title

entity.insanelib.area_effect_cloud_3D
It was when I was using the Champions mod along with other mods that put mini-bosses (i forgot the other mods I used).
and when I kill them the effect cloud is still there.

and when I go to the video setting and particles and disable the entity particle 
the cloud disappears in my screen but whenever I point my cursor to where the cloud effect used to be. The jade says it's still there.

**Comment by Insane96** [comment]
It's probably not compatible with Champions

**Comment by EmoBubbleGum** [comment]
Just disable it in the insanelib config if it's giving you issues
