### ISSUE TITLE
Update: no longer incompatible or never was incompatible with Optifine

### ISSUE THREAD

**Issue by Barerock** [Insane96/InsaneLib#22]
As of OptiFine_1.20.1_HD_U_I6, this mod does not crash when loaded together. I'm not sure if it ever did crash, but I know that InsaneLib-1.12.1-mc1.20.1 is stable (if anything can be stable with Optifine).

Referencing the year old crash report some guy made that is no longer in my clipboard.

**Comment by Insane96** [comment]
Optifine is not supported. Use Embeddium
