### ISSUE TITLE
[BUG] 1.20.1 - crash when breaking an end crystal (punching, etc). World-corrupting crash. 

### ISSUE THREAD

**Issue by muggleorwizard** [Insane96/InsaneLib#24]
[latest.log](https://github.com/user-attachments/files/17088010/latest.log)

When an end crystal is spawned by a chance cube or by being placed by a player, breaking that end crystal will cause a world-corrupting crash. World can not be rejoined.

**Comment by muggleorwizard** [comment]
The crash occurs using version 1.15.0-mc1.20.1, does not occur on 1.14.0-mc1.20.1

**Comment by Insane96** [comment]
Progressive bosses 3.9.7 is not compatible with latest InsaneLib

**Comment by muggleorwizard** [comment]
If that's the case, then I'd recommend either putting the latest insanelib as alpha, or latest progressive bosses as a release. As it currently stands, if you install the latest release of progressive bosses (3.9.7) and the latest release of insanelib (1.15.0), the crash will occur. No option to update progressive bosses unless you manually go into the alphas.

**Comment by muggleorwizard** [comment]
Or at least a note on your project pages about the world-corrupting incompatibility

**Comment by Insane96** [comment]
> insanelib as alpha, or latest progressive bosses as a release

InsaneLib is not in Alpha and PB is not in release. 

> Or at least a note on your project pages about the world-corrupting incompatibility

World corrupting incompat?

**Comment by muggleorwizard** [comment]
For 1.20.1, PB 3.9.7 is listed as latest release on curseforge and IL 1.15.0 is latest release. When both are installed, the end crystal corrupting crash can occur. Players might not know that they need to switch from the latest release of PB (3.9.7) to an alpha build to prevent this incompatibility.
![Screenshot_20240922_103406_Firefox](https://github.com/user-attachments/assets/6732047e-ec03-459d-93c1-0ba570e286b0)

**Comment by Insane96** [comment]
Ok, how is that a world corrupting incompatibility?

**Comment by muggleorwizard** [comment]
> Ok, how is that a world corrupting incompatibility?

Back to the original issue - when both are installed and you try and break an end crystal, the world will crash and corrupt. Rejoining the world is impossible. (Tested by placing end crystal item and then trying to break it)

**Comment by Insane96** [comment]
> Rejoining the world is impossible

That should 100% not happen

**Comment by muggleorwizard** [comment]
> > Rejoining the world is impossible
> 
> That should 100% not happen

I agree. But, as you said, the two versions are not compatible.
