### ISSUE TITLE
After loading a saved game and entering the world, the game experiences prolonged freezing.

### ISSUE THREAD

**Issue by tsubfak13** [Insane96/InsaneLib#26]
Steps to Reproduce:

Enter the game world.
Observe the prolonged freezing issue.

Additional Information:

Minecraft Version: 1.20.1
Forge Version: 47.3.12
InsaneLib Version: 1.15.1
I have identified that the prolonged freezing issue after loading into the game world is caused by the InsaneLib mod. However, I am uncertain which other mod might be conflicting with it. I have attached my modpack and log files for your reference. Notably, I did not load any KubeJS or other mod configurations or scripts during troubleshooting; everything was set to default.
logs:
[latest.log](https://github.com/user-attachments/files/17998723/latest.log)
My modpack:
[GregtronixRevolution-1234.zip](https://github.com/user-attachments/files/17998731/GregtronixRevolution-1234.zip)

**Comment by Insane96** [comment]
Not gonna test your modpack for you.
Find the problem with spark.
